### ISSUE TITLE
[Bug Report]: Gamesir T1s  bluetooth not recognized / can't connect (should be working since MissionControl 0.4.1 ?)

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [ndeadly/MissionControl#380]
### Switch Firmware Version

13.0.0 (Latest)

### Atmosphère Version

1.1.1 (Latest)

### Mission Control Version

0.6.0 (Latest)

### Boot Method

Hekate

### Issue Description

Gamesir T1S not recognized (neither bluetooth nor USB conencted)
_My Gamesir G4S worked perfectly on bluetooth, so i think my Mission control is well installed_

### Error Report

T1S Not recognized
I saw you did a custom 0.4.1 version of mission control here to fix T1S controller : https://github.com/ndeadly/MissionControl/issues/184
But i can't use it since i'm only on latest versions of Hekate/atmosphere/firmware :(

### Additional Context

_My Gamesir G4S worked perfectly on bluetooth, so i think my Mission control is well installed_

**Comment by Darcidride** [comment]
1. The Gamesir T1S controller won't connect at all
2. I can't tell you if the buttons works because it can't connect itself
3. I tried all different mode possibility (android, ios, xinput, mouse), but it's working in Android mode for G4S so i guess it should be the same for T1S
4. Ok, it's what i was thinking, it should be working right now with latest build of MissionControl

Tell me if i can help you by doing anything (debugging/testing/etc.)

**Comment by otto-dev** [comment]
I do own this controller and can confirm that it indeed DOES work with `MissionControl`.

Press `A` (on the controller) while turning it on to put it into Android mode. It may take a few tries until the switch picks it up. Also try pressing `B` when turning it on.

**Comment by BetterToAutomateTheWorld** [comment]
@otto-dev The `Power` + `A` is the way we start the GameSir T1s in Android mode, I don't think we can miss it, but thank you anyway !

@ndeadly Thank you for your support, I removed all MissionControl folders/files and then reinstalled the 0.6.0-debug version you sent, and it's working fine, the pairing was almost immediate (under 5 seconds). This makes me think between the 0.4.1 and 0.5.0 version I tested, maybe I had residual/corrupted MissionControl config files...

To be sure everything was working perfectly, I tried 0.6.0, then 0.6.1, then the latest release you published yesterday (0.6.2), and all of these releases are working like a charm ! :)

PS : Just in case you're curious, and want to ensure T1s is working fine in 0.6.0, here is the `bluetooth-mitm.log` I got with the debugging build [t1s-bluetooth-mitm.log](https://github.com/ndeadly/MissionControl/files/7562487/t1s-bluetooth-mitm.log)

**Comment by otto-dev** [comment]
>  I don't think we can miss it

Well you missed something - just trying to help.
Glad it works. :+1:

**Comment by ndeadly** [comment]
@BetterToAutomateTheWorld thanks for following up. Not really sure what happened there, but I think it's safe to say that something must have gotten into an incosistent state. Took at look at the log, everything looks normal with no evidence of any failures. Glad to know it's working for you now :)
