### ISSUE TITLE
[Bug Report]: Fire emblem three houses. Constant random vibration pulses

### ISSUE THREAD

**Issue by Dashinginthe90s** [ndeadly/MissionControl#418]
### Switch Firmware Version

13.2.0 (Latest)

### Atmosphère Version

1.2.5 (Latest)

### Mission Control Version

0.6.3 (Latest)

### Boot Method

Fusée

### Issue Description

When launching fire emblem three houses the controller starts randomly pulsing the vibration motors. Happens both on the main menu and in game.
Opening the home menu stops the vibrations while it is open. 
Turning off vibrations in the game settings menu also stops them.
No issues with vibrations in any other game.
Official joycons and the pro controller do not have this issue.

This appears to be a general issue with third party controllers in this game. My magic-ns adapter does the same thing on a stock switch not running Atmosphere or mission control.
The 8BitDo adapter also has a note about this in their firmware update changelog

> 10/23/2019
> Fixed the abnormal vibration problem of the game "Fixed Fire Emblem: ThreeHouses" on switch console.

**Comment by ndeadly** [comment]
Thanks for the report. Which version of the game are you running? I will try to get my hands on a copy and investigate. 

This sounds similar to the issue I fixed recently regarding the Crash Bandicoot games. I think what is happening is that these games are erroneously outputting rumble packets with frequency/amplitude parameters that are outside of the range reproducible by the official HD rumble motors (and so don't get picked up during testing) , but when converted to work on a controller with regular rotating mass motors get transformed into actual vibrations.

**Comment by Dashinginthe90s** [comment]
The title screen says v1.20
My copy is from the NA eshop and I have the latest update installed.

**Comment by ndeadly** [comment]
Does this still occur with the latest firmware and Atmosphere/Mission Control versions? I finally managed to get my hands on a copy of the game, but am unable to reproduce the issue.

**Comment by swordgit** [comment]
Updated to the latest version, and issues still exists
Switch Firmware Version
14.1.1

Atmosphère Version
1.3.2

Mission Control Version
0.7.0

Boot Method
Fusée

**Comment by ndeadly** [comment]
This should be fixed now in the latest release https://github.com/ndeadly/MissionControl/releases/tag/v0.12.0
