### ISSUE TITLE
Hori ONYX PS4 controller support 

### ISSUE THREAD

**Issue by MarkoVu12** [ndeadly/MissionControl#68]
![DmlykMjVAAAQl3C](https://user-images.githubusercontent.com/34967638/92997960-535edc00-f517-11ea-9ca3-9c2ae1facb1a.jpg)
Hi again mate! It would be awesome to add this one, if possible :) I was trying to pair it, but no luck.  I was able to test this one and it works great with Sys-Con over cable. Thanks again.

**Comment by ndeadly** [comment]
Could you try pairing the controller with the switch and post the output from btdb.nro? It won't show as connected to the console but will still connect and get added to the database if the pairing completes successfully.

Is this a 3rd party PS4 controller? Might only need to whitelist the hardware ID if that's the case.

**Comment by MarkoVu12** [comment]
Thanks for the fast reply! Unfortunately, i can't pair it.. I also disconnected all controllers.. Only my old DualShock 4 is connected at the moment. And yes, this is a 3rd party PS4 controller :)
![Album_9_12_2020_5_34_51_PM](https://user-images.githubusercontent.com/34967638/92999137-e6e7db00-f51e-11ea-91ab-a73b29a5193a.jpg)

**Comment by ndeadly** [comment]
Are you sure you're putting it in sync mode correctly? This is a thing a lot of users mess up on the DS4. Don't know if the Hori uses the same button combo or what though. Are you able to pair it to a PC or phone?

Otherwise I'll have to knock you up a debug logging build later when I have time so you can log the pairing process. It's either rejecting the connection, or not seeing the controller it all. The first one we can probably work around. If it's the latter it may be an incompatibility with the switch bluetooth hardware/driver and there's not much I can do. I had a user with a 3rd party WiiU controller report similar.

**Comment by MarkoVu12** [comment]
Yes, all good with pairing. I was able to pair it with my PC and Android phone. It pairs quickly on both, but i can't use it on those two for some reason.  Btw, it seems that this controller only charges connected to my PS4. Tried to charge it on the Switch and by plugin it to a phone charger but no luck..

**Comment by ndeadly** [comment]
I would try a few times more with the switch just to be sure. Put it in pairing mode and leave it at the Change Grip/Order screen for maybe 30 secs. Failing that you'll need to log the connection attempts for me when I'm able to build you a logging version.

I'm not sure what the charging behaviour of various controllers is, but it's likely something out of my control.

**Comment by MarkoVu12** [comment]
I disconnected all controller again, connected HORIPAD Zelda Edition first, then i tried to search it again like you said and this bad boy popped up  :)
![Album_9_12_2020_7_04_36_PM](https://user-images.githubusercontent.com/34967638/93000809-fa993e80-f52a-11ea-8834-187e8666f4b2.jpg)

**Comment by ndeadly** [comment]
Nice :) That's annoying that they both use the same hardware ID of `0f0d:00f6`. That could cause problems if they've used it for other controller types too. For now it's safe though because official Switch controller names like `Lic Pro Controller` are searched first.

I've whitelisted that hardware ID in this build. It's probably all that's required to work since this controller is meant for PS4.
[MissionControl-0.2.0-hori-onyx.zip](https://github.com/ndeadly/MissionControl/files/5213032/MissionControl-0.2.0-hori-onyx.zip)

**Comment by MarkoVu12** [comment]
I salute you sir!! <3
![56630393](https://user-images.githubusercontent.com/34967638/93001521-dd1aa380-f52f-11ea-9707-cb942b5852f8.jpg)
Everything works perfectly!!

**Comment by ndeadly** [comment]
Sweet. This will be included in the next release. You can continue to use the build I posted for now though.

**Comment by MarkoVu12** [comment]
Just to add, DualShock works just by pressing a home button, Onyx needs to be synced everytime. Other than that, all is perfect my friend.

**Comment by ndeadly** [comment]
Is that the case on PS4 too? You really shouldn't need to sync any controller more than once. I think there's something a little out of spec with some of the Dualshock4 hardware. People with official v1 DS4 controllers seem to have issues with them taking a while to connect also.

Anyhow, this is likely nothing I can change if it doesn't, because the actual Bluetooth link is established at the hardware/driver level.

**Comment by MarkoVu12** [comment]
Don't have that issue on PS. I have. V1 DS4 and can confirm that. But after pairing, it's fast! God bless brother! :)

**Comment by MarkoVu12** [comment]
Hi friend! Since recently, this controller is not working or showing in database at all :/ I had to remove all paired controllers, and after that, tried all of your versions of Mission Control, no luck. Please help me if you can. Thanks again!

**Comment by ndeadly** [comment]
Which firmware version are you on? 12.0.0 overhauled a lot of the bluetooth code and initially broke a bunch of controller's ability to pair. That was fixed in 12.0.1 though, and I've since patched the other issues I was aware of for other controllers in the latest Mission Control (0.5.0). 

This controller was a little difficult to get to pair originally wasn't it? You might need to just keep trying. Does the controller have a reset button like regular PS4 controllers? I've heard this can improve the reliability when they're refusing to pair.

**Comment by MarkoVu12** [comment]
I'm currently on 12.0.2 with Ams 19.3. Should i update to the latest firmware? Yes, this one was really pain in the @ss... I also did the reset button thing, no luck :/ Yes, reset button is pretty much the same like on the DS4. Thanks again!

**Comment by ndeadly** [comment]
Does the latest Mission Control (non pre-release) even work with ams 0.19.3? Unless you have a reason not to, I would update HOS, ams and Mission Control to the latest versions, just in case there have been improvements to something inside the bluetooth module since 12.0.2

If you still can't get it to work after multiple pairing attempts you could try creating me a log with this build. I can't promise the log will allow me to make it work, but it might at least give some insight into what's happening. The log will be created in `sdmc:/bluetooth-mitm.log`

[MissionControl-0.5.0-dbg-21c541d.zip](https://github.com/ndeadly/MissionControl/files/6826165/MissionControl-0.5.0-dbg-21c541d.zip)

**Comment by MarkoVu12** [comment]
Just to confirm it, yes, it does with my V1 DS4.. My friend, i updated everything
HOS version: 12.1.0
AMS version: 0.19.5
MC  version: 0.5.0-dbg-21c541d

Still no luck to find Onyx. Here is the log.

Thanks
[bluetooth-mitm.log](https://github.com/ndeadly/MissionControl/files/6826425/bluetooth-mitm.log)

**Comment by ndeadly** [comment]
Hmm, looks like it _is_ being detected and begins the authentication process but ultimately fails. The same thing happens to DS4 controllers when they take a while to pair though, so this isn't anything out of the ordinary. I don't really know what causes this to happen in either case, it's not exactly a complicated process. Maybe a timeout or something...

Anyhow, only thing I can suggest for now is to keep trying (yeah I can see you already did that a fair bit). It's getting late here, but I'll try to make you a special build of ams 0.19.5 tomorrow that can log the commands of the bluetooth stack which might give some more info about what's actually failing.

**Comment by MarkoVu12** [comment]
Can't thank you enough sir! Ok, no problem, it's late here too, looking forward for tomorrow, so we can continue this project. Good night. 😃

**Comment by MarkoVu12** [comment]
Just to add, tried to detach both Joy Cons while pairing, no results.

**Comment by ndeadly** [comment]
Sorry I didn't get this up earlier, built it but forgot to upload it before I went out of town for the weekend. Documentation on the uart logging and how to enable it can be found [here](https://github.com/Atmosphere-NX/Atmosphere/blob/c9dd93687bbc2838150c0d965d8ada3c5cfea0c1/docs/components/modules/ams_mitm.md#uart_mitm)

[atmosphere-0.19.5-uart_mitm-3694d7a4-dirty.zip](https://github.com/ndeadly/MissionControl/files/6843606/atmosphere-0.19.5-uart_mitm-3694d7a4-dirty.zip)

**Comment by MarkoVu12** [comment]
No problem, mate! Hey, I'm totally lost in enabling this uart_mitm line in system_settings.ini
I looked everywhere for this :/

**Comment by ndeadly** [comment]
The file isn't present by default. If you don't already have an `/atmosphere/config/system_settings.ini` you should copy the one from `/atmosphere/config_templates/system_settings.ini` and uncomment or add the line in there.

**Comment by ndeadly** [comment]
Sorry, that above build was broken I think. I assumed because it built correctly that it would be fine, but I tried it myself for testing something and it wouldn't boot. This one should work.

[atmosphere-0.19.5-uart_mitm-cf40d57a-dirty.zip](https://github.com/ndeadly/MissionControl/files/6861765/atmosphere-0.19.5-uart_mitm-cf40d57a-dirty.zip)

**Comment by MarkoVu12** [comment]
Thanks, @ndeadly !!! I moved Atmosphere, Sept and Switch folder and moved your zip files on my sd card.. Then moved system_settings_ini from /atmosphere/config_templates/system_settings.ini to /atmosphere/config/system_settings.ini and added line enable_dns_mitm = u8!0x1 under [atmosphere] and then again in NOTE: EXPERIMENTAL. After trying to pair Onyx, there is no /atmosphere/uart_logs.. Sorry, I'm a total noob in this.

**Comment by ndeadly** [comment]
No problem. I set this up with someone earlier and had similar confusion with the `enable_dns_mitm` thing. I don't know what's happened to the ini file but it should read 

```
; Controls whether to enable uart mitm
; for logging bluetooth HCI to btsnoop captures.
; This is only implemented for [7.0.0+].
; 0 = Do not enable, 1 = Enable.
; enable_uart_mitm = u8!0x0
```

It's the `enable_uart_mitm ` key you want to set to 1

**Comment by MarkoVu12** [comment]
I see :)  One more question, can i move your system_settings_ini file to mine Atmosphere\config? And we i don't need it anymore, can i delete it from there, and put back like it was in Atmosphere\config_templates? Thanks

**Comment by ndeadly** [comment]
You can just delete it from `/atmosphere/config` when you're done. You'll reinstall normal atmosphere when you've made the log and that will restore the original template

**Comment by MarkoVu12** [comment]
I Think i made it  :) Sorry for didn't put just the 4th file, but this is all from logs. 
[uart_logs.zip](https://github.com/ndeadly/MissionControl/files/6864348/uart_logs.zip)

**Comment by ndeadly** [comment]
So that's the right thing, but I don't see any evidence of the controller in there. Were you attempting to pair it when you made the log?

**Comment by MarkoVu12** [comment]
Nice! Yep, tried that and also leave it for 30 secs on pair screen. I will try again with DS4 too. Should i have to put Mission Control for this? Those 3 files are empty, just the Switch one. Thanks

**Comment by ndeadly** [comment]
Yes, you will need mission control running or else the console will never attempt to pair with unsupported controllers. And yeah, it's normal for the first 3 logs to be empty. The 4th one is always the one that contains the bluetooth log.

**Comment by MarkoVu12** [comment]
Got it! I will have to go outside for a while, will do this asap. Thanks again for everything

**Comment by MarkoVu12** [comment]
So this results are with a fresh SD card
[uart_logs.zip](https://github.com/ndeadly/MissionControl/files/6868519/uart_logs.zip)
Btw, with both SD cards, when i try to go to album folder, Switch crashes with error 0100000000001000
Thank you

**Comment by ndeadly** [comment]
Hmm still not a lot in there, but I can see that the controller name is showing up in there. It looks like the process is not getting very far at all. I will take a better look at it over the weekend when I have time.

> Btw, with both SD cards, when i try to go to album folder, Switch crashes with error 0100000000001000

This will happen if you created a new atmosphere folder instead of merging with an existing install, as self-compiled zips don't include hbmenu.nro or hbl.nsp. You can copy these from an official release if you need to be able to launch hbmenu.

**Comment by MarkoVu12** [comment]
Oh, ok. After putting hbl.nsp file, there is no crash. Mission control can't see it, but here is another log
[01627056273_00202377573_010000000000000b.zip](https://github.com/ndeadly/MissionControl/files/6869997/01627056273_00202377573_010000000000000b.zip)
Cheers 🥇
